# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# Language setting for CodeRabbit (English)
language: en-US

# Guidelines defining the AI coach's personality and review style
tone_instructions: >
  Focus on improvements rather than criticism; follow P1–P5 priority labels; include helpful document references and light, witty praise.

# Code review settings
reviews:
  profile: chill # Review style: relaxed and friendly tone
  request_changes_workflow: false # Do not block merge when requesting changes
  high_level_summary: true # Provide a high-level PR summary
  changed_files_summary: false # Disable per-file summaries (avoid redundancy)
  sequence_diagrams: false # Do not generate sequence diagrams
  assess_linked_issues: true # Analyze linked issues
  related_issues: false # Do not suggest related issues
  related_prs: false # Do not suggest related PRs
  suggested_labels: false # Do not suggest labels
  auto_apply_labels: false # Do not auto-apply labels
  suggested_reviewers: false # Do not suggest reviewers
  auto_assign_reviewers: false # Do not auto-assign reviewers
  poem: true # Write a short poem after the review (for fun)

  # Path-specific review guidelines
  path_instructions:
    - path: src/**
      instructions: |
        ## Review Guidelines
        - Follow team conventions, readability, and exception handling.
        - Ensure testability, maintainability, and modular design.
        - Review API, DB, and security design for potential issues.
        - Identify unnecessary logic, apply clean code principles.
        - Verify service/domain separation and extensibility.
        - Maintain consistent team style and patterns.
        - Prioritize critical or security-sensitive issues first.

        ## Priority Levels (P1–P5)
        - **P1:** Must fix — security vulnerabilities, crashes, or data loss.
        - **P2:** Should fix — performance or architecture violations.
        - **P3:** Nice to fix — readability, refactoring, or naming issues.
        - **P4:** Optional — minor improvements, stylistic preferences.
        - **P5:** Informational — personal opinions or FYI comments.

        ## Testing
        - If tests are missing, suggest what tests to add:
          - Controller → Integration (E2E) tests
          - Service/Utils → Unit tests
        - Use `given-when-then` pattern for clarity.

        ## Review Principles
        - Feedback should focus on code, not people.
        - Use constructive tone (“You could improve this by…”) instead of criticism.
        - Discuss with reasoning and examples when proposing changes.
        - Praise good code; silence isn’t always enough.

  # Auto-review behavior
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: false
    base_branches: ['.*']

  # Analysis tools
  tools:
    hadolint:
      enabled: true
    gitleaks:
      enabled: true
    sqlfluff:
      enabled: true

# Chat and interaction settings
chat:
  auto_reply: true

# Knowledge base configuration
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local

# Code generation
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: src/**
        instructions: |
          - Use official Javadoc-style docstrings in English.
          - Include method purpose, parameters, return values, and exceptions.
          - For public APIs, document in detail; for internal methods, summarize concisely.

  unit_tests:
    path_instructions:
      - path: src/**
        instructions: |
          - Controllers: integration (acceptance) tests for API endpoints.
          - Other layers: unit tests for functions/classes.
          - Use given–when–then pattern.
